### PR TITLE
Add sound capture

### PR DESCRIPTION
**Pull request by dz0ny**
Ref: https://github.com/phw/peek/issues/105

For future reference https://github.com/EasyScreenCast/EasyScreenCast/blob/master/utilgsp.js#L19, this file can be quite useful. 

On
image

Off
image

### CODE REVIEW

**Comment by dz0ny** [comment]
@phw Rebased of master

**Comment by phw** [comment]
For hiding / showing the label see how this checks for `SMALL_WINDOW_SIZE` in `application-window.vala`. The same could be applied to the sound capture button. Adjusting `SMALL_WINDOW_SIZE` needs to be done manually and depends a bit on the theme, but the current settings seems to work well mostly.

**Comment by dz0ny** [comment]
> Thanks a lot for this and sorry for the lack of reply. Still trying to catch up on Peek development again :(
> 
> About the patch: I think we could include it, but my main issue with this currently is the additional used space in the header. So far we took great care that the Peek window can get as small as possible.
> 
> I think for a first version this option should only be present in the options, not in the header bar. If we really want this also in the header bar it should be in a way that uses as less space as necessary. That means:
> 
> 1. Only who an icon. A label could still be shown if the window size is large enough
> 2. Only show the control if a format is selected that supports this (not for GIF)

Implemented both changes in the latest commit.

**Comment by dz0ny** [comment]
An icon is almost a must since I did recording a couple of times without actually recording the sound, So it's kinda UX helper, the problem with icon itself is that there is no "muted microphone icon in gnome".

**Comment by adrianocr** [comment]
Any update on this? Really looking forward to it.

**Comment by thautwarm** [comment]
Merge this please, really want it...

**Comment by thautwarm** [comment]
Hi @dz0ny, just have tried your fork, when the video gets a little longer, the saving/rendering will be endless.

**Comment by dz0ny** [comment]
> Hi @dz0ny, just have tried your fork, when the video gets a little longer, the saving/rendering will be endless.

As you can see https://github.com/phw/peek/pull/362/files#diff-a40fecfa2fd7ff0bb7c0225ee8714ee1R28

It only applies most basic defaults, my assumption is that you are missing some basic codecs in your build of FFmpeg or GStreamer.

Try running peek from the command line, thats should give us the error.

**Comment by gueorgui** [comment]
This would be really nice to have.

**Pull request closed without merging**
