### PR TITLE
New application icon

### PR DESCRIPTION
**Pull request by phw**
See #114

### CODE REVIEW

**Comment by gort818** [comment]
Looks awesome! Thanks @bertob

**Comment by phw** [comment]
@snwh, @jimmac, @lapo: How would you like to be credited here for the icon? Thanks for your work, it's awesome!

**Comment by jimmac** [comment]
Is this blocking on vanity? ;) 

The aboutbox is quite exposed and perfect fine from my POV.

**Comment by snwh** [comment]
About box/name only credit is fine by me as well.

**Comment by bertob** [comment]
Can we merge this? :)

**Pull request merged**
