### PR TITLE
i3 readme update

### PR DESCRIPTION
**Pull request by McKean**
So basically peek works very nicely with i3 if you just stack it with the intended window you want to record.
Tested and works fine on my setup, as I've read many people have issues with i3 and peek and I had too, I think it's best addressed here.

Thank!

### CODE REVIEW

**Comment by sQVe** [comment]
I cannot get this to work. The instructions are a bit fuzzy, what do you exactly mean by "stack it with the intended window"?

**Comment by phw** [comment]
I wanted to test this myself before merging anything, but don't have the time for it right now. But for all that I know i3 does not support the X shape extension, and without this the click through cannot work AFAIK. See also https://github.com/i3/i3/issues/2742 .

@McKean Is clicking and interacting with the recorded content possible for you or just the recording? Do you have a compositor (e.g. compton) running?

**Comment by sQVe** [comment]
I'm not getting it to click through eventhough I'm floating both windows with peek on top. I'm also having issues with the tmp file having no content in it when I use i3.

**Comment by McKean** [comment]
@sQVe see this screenshot: https://dl.dropbox.com/s/iq3jrzxl86ioxgw/shot-2017-10-26-17-54-50.png?dl=0  
@phw yes I'm using compton, I'm not sure if it works without.

One thing that would be beneficial is to be able to start peek without that top bar, that way it would record the whole window which is stacked (you can see in the screenshot that it will not capture the top part). Other than that it works really well.

**Comment by McKean** [comment]
i3 stacked windows no compton:
screenrecording

**Comment by sQVe** [comment]
I can now confirm that using either `stacked`, `tabbed` or floating both windows (peek and the window to be recorded) in i3 is working to record with _peek_ :+1:.

**Comment by McKean** [comment]
@sQVe great to hear, instread of using the two floating windows approach I would recommend using the scratchpad method, where you put Peek into a scratch pad if you want to have a well defined area to record.

**Comment by phw** [comment]
I am not an i3 user, but I think now I get it. While click-through is not working on i3, i3 is flexible enough to do with Peek whatever you want, also having it ignore Peek's wish to be always on top and send it to that hidden scratchpad workspace where it is not visible but still maintains its coordinates. Is this about right?

Thanks for this addition to the documentation.

**Comment by sQVe** [comment]
@phw That is correct. There are plenty of different ways for it to work with i3. :+1:

**Comment by McKean** [comment]
@phw yeah that's pretty much it. Also the reason why I'm requesting: https://github.com/phw/peek/issues/203  
But perhaps I should just try and contribute towards such a feature myself :)

**Pull request merged**
