### PR TITLE
"DesktopUtility" is an unregistered value, so it should start with "X-"

### PR DESCRIPTION
**Pull request by csmk**
I stumbled upon this by running the desktop-file-validate tool (:

### CODE REVIEW

**Comment by phw** [comment]
Do other apps use X-DesktopUtility? I would see not much sense in a category not in use.

@Mailaender You added this in https://github.com/csmk/peek/commit/e7375ec16b514ca66f09a766dc088994d70d06dc, what was the exact reason for it.

**Comment by Mailaender** [comment]
You need to define a sub-category, but you are right, I chose an invalid one according to https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#Utility

**Comment by csmk** [comment]
So, shouldn't it be `Categories=GTK;GNOME;Graphics;2DGraphics;`?

**Comment by Mailaender** [comment]
Yes, maybe even `Categories=GTK;GNOME;Graphics;2DGraphics;RasterGraphics;`. I think I copied the category from the `shutter.desktop` https://launchpad.net/shutter which in retrospect wasn't a good template. Sorry.

**Comment by phw** [comment]
Thanks for the input. Do we really need the sub category? I think Utilities is a rather fitting category given the simplistic nature of Peek, also the Gnome screenshot tool uses `GTK;GNOME;Utility;X-GNOME-Utilities;`

Also I can't find anything in the menu spec that a sub category is required, https://standards.freedesktop.org/menu-spec/latest/apas02.html just says it can be used. And looking through the desktop files on my system plenty specify just a main category.

I mean `Categories=GTK;GNOME;Graphics;2DGraphics;` could be an option, but I tend toward dropping the sub category as I can't find anything fitting.

**Comment by Mailaender** [comment]
The @openSUSE build service rpmlint is kinda strict will error the build and delete all binaries so I will be forced to patch in a second category. I assume this is required to make it look good on the hierarchical KDE menus and SUSE was traditionally very KDE focussed.

**Comment by phw** [comment]
@Mailaender Will te openSUSE build accept something outside that list you linked, e.g. anything starting with "X-"?

**Comment by Mailaender** [comment]
Yes, I think the `X-` prefix will result in an ignore for the check script and most desktops will then sort the utility in a category like "other" or "misc".

**Pull request merged**
