### PR TITLE
Fedora Spec file and Repo for peek installation

### PR DESCRIPTION
**Pull request by Bajoja**

### CODE REVIEW

**Comment by phw** [comment]
Thanks a lot

**Comment by phw** [comment]
@Bajoja Can you review my changes on https://github.com/phw/peek/commit/1cbd135b7f2d3d94c36b82836dcc8b9c374ddc43#diff-2158217562061121145ed8bd1cae555a?

Current git version requires libkeybinder3 library and I added it to the spec file as I thought it probably should be added, but no experience with building for Fedora :)

**Comment by Bajoja** [comment]
@phw that's correct.

**Comment by phw** [comment]
Thanks for checking

**Comment by phw** [comment]
@Bajoja Just noticed I broke the icon name, the line

    %{_datadir}/icons/hicolor/*/apps/com.uploadedlobster.peek.%{name}.png

Should of course not include .peek :) Sorry for that, will fix here.

**Comment by Bajoja** [comment]
@phw i wiil take care of this soon, i wiil make a pull request to fix this

**Comment by phw** [comment]
Thanks :) Already fixed here https://github.com/phw/peek/commit/9d469320eb8014a16f5a35c7f24fcbefe40f03e0

But of course let me know of any other changes required, as I did al the canges without actually testing.

**Comment by Bajoja** [comment]
@phw Ok i will test and launch 1.0

**Pull request merged**
