### PR TITLE
Generate po/LINGUAS based on all translation files

### LINKED ISSUE #50: Automate generation of LINGUAS file
So far I have manually updated this file, but it should be autogenerated during build.

### PR DESCRIPTION
**Pull request by krobelus**
Fixes #50

### CODE REVIEW

**Comment by phw** [comment]
Thanks a lot for this

**Comment by krobelus** [comment]
I noticed this generation is only done a configuration time but not at build time. So this might not be what we want.
I also found a simple way to do it in meson at configuration time. It may be enough to force a reconfigure if the contents of po/ have changed.

**Comment by phw** [comment]
@krobelus Yes, right. Maybe it could also be just a separate task that can be run on demand, I think that would be sufficient in most cases. Maybe just before the po files get updated (target `update-po` in CMake, I think I don't yet have a target for it in Meson).

And yes, going forward it looks like Meson will be used. I like it very much so far and will likely merge the Meson branch soon. I will keep CMake in parallel for a while and see if everything is fine (I have to see how this complicates builds on older systems that don't provide Meson).

**Comment by phw** [comment]
Ok, I've merged the Meson build. There was already a target for updating po files (`peek-update-pot`). A reason more for liking Meson, the whole gettext thing is fully supported with only a single line build script :)

So if you want to see how to add this LINGUAS update to Meson got ahead :)

**Comment by krobelus** [comment]
Yes, meson looks very good so far.

After looking into this further, it might not be a good idea to generate LINGUAS from within the build system. In order for msgfmt to work, LINGUAS has to be located in the same directory as the translation files, so it needs to be in the source tree.

From the meson documentation at http://mesonbuild.com/Running-Meson.html
> Meson will not under any circumstances write files inside the source directory (if it does, it is a bug and should be fixed).

I consider that a sensible approach because it's dangerous to edit generated files.
So I think to generate LINGUAS we should maybe just have a tiny script in `tools` which makes it explicit that it changes the file inside the source tree.

Additionally, we could have meson check that all *.po files actually show up in LINGUAS. Similar to [this](https://github.com/gnome-mpv/gnome-mpv/blob/master/po/meson.build), they just do it it other way round, verifying that all entries in LINGUAS have a corresponding translation file. However, it is probably nicer to optionally have these checks in the gettext meson module.

**Comment by phw** [comment]
> I consider that a sensible approach because it's dangerous to edit generated files.
> So I think to generate LINGUAS we should maybe just have a tiny script in tools which makes it explicit that it changes the file inside the source tree.

I am not against putting this into a script file. But note that meson also supports so called [run targets](http://mesonbuild.com/Run-targets.html) that are supposed to just add a target to invoke an external command, and that is meant to help in development tasks that actually could manipulate source files. Actually the `peek-update-po` target defined by the i18n module does this. The rule meson does not write to the source files is only true for the build itself, and updating the LINGUAS file is not part of the build but a development task.

**Comment by krobelus** [comment]
Sorry for the long delay..
Yeah, it makes sense to use a run target, I learnt something new :)
I did it in https://github.com/phw/peek/pull/328. So https://github.com/phw/peek/pull/320 should probably be reverted.

**Pull request merged**
