### PR TITLE
Add sound capture settings

### PR DESCRIPTION
**Pull request by dz0ny**
ref: https://github.com/phw/peek/issues/105 and https://github.com/phw/peek/pull/362

### CODE REVIEW

**Comment by soredake** [comment]
@phw

**Comment by Aikufurr** [comment]
Downloaded source and added changes as shown in this PR and built for [Debian](https://github.com/phw/peek#debian) (Kubuntu 21.04) and can confirm recording audio works great and makes peek so much more handy for quick regional screen recording.

**Comment by ptrsmk** [comment]
Can we get this merged?

**Comment by phw** [comment]
Sorry for the extremely long delay. I'm trying to get back to this app and finally give it the deserved attention again. Thanks a lot for your patch here, merging

**Comment by rakshit087** [comment]
Is it available for Ubuntu too?

**Comment by soc** [comment]
It appears that Peek now records audio, even if the option is disabled:

record-audio

Is this intentional?

**Comment by kachar** [comment]
@dz0ny I can report the same as @soc.
The latest version does record audio silently even when the `Capture sound` setting is not enabled.

**Comment by dz0ny** [comment]
The one option possible is that settings is never saved (try removing settings), other than that no. It uses extended command line params to do configure input device recording.

**Comment by soc** [comment]
Can we get this fixed?

**Pull request merged**
