### PR TITLE
Create sv.po

### PR DESCRIPTION
**Pull request by eson57**
Hi,

Here's Swedish translation if wanted. Nice app! :+1:

### CODE REVIEW

**Comment by phw** [comment]
Thanks a lot for this, merged :) I have also synced it with Transifex, you should be able to join the language team there

**Comment by eson57** [comment]
Yes, thanks. I hoped for that. :+1:

**Comment by phw** [comment]
@eson57 FYI, I have moved translations from Transifex to Weblate, see https://github.com/phw/peek/issues/36#issuecomment-261588876 for details

**Comment by eson57** [comment]
Yes, thanks! That is noted.

**Pull request merged**
