### PR TITLE
Completed it.po

### PR DESCRIPTION
**Pull request by pharaone**

### CODE REVIEW

**Comment by phw** [comment]
Cool, thanks

**Comment by phw** [comment]
The build errors with

```
/home/travis/build/phw/peek/po/it.po:76: 'msgid' and 'msgstr' entries do not both end with '\n'
```

Can you take a look?

**Comment by pharaone** [comment]
Fixed, sorry for before

**Comment by pharaone** [comment]
Now it works!

**Comment by phw** [comment]
grazie mille

**Comment by pharaone** [comment]
Prego!

Il 13 ott 2017 5:28 PM, "Philipp Wolfer" <notifications@github.com> ha
scritto:

**Comment by phw** [comment]
@pharaone There are a couple of strings marked as "fuzzy" / needing review, see https://hosted.weblate.org/translate/peek/translations/it/?type=fuzzy

Are those ok?

**Comment by pharaone** [comment]
Yes, I don't know why are marked as fuzzy

Il 14 ott 2017 6:31 PM, emanueleant03@gmail.com ha scritto:

Yes, I don't know why they are

Il 14 ott 2017 6:30 PM, "Philipp Wolfer" <notifications@github.com> ha
scritto:

@pharaone <https://github.com/pharaone> There are a couple of strings
marked as "fuzzy" / needing review, see https://hosted.weblate.org/
translate/peek/translations/it/?type=fuzzy

Are those ok?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/phw/peek/pull/193#issuecomment-336646672>, or mute the
thread

**Pull request merged**
